# Site Settings
title:               Lagrange
tagline:             a minimalist Jekyll theme
description:
baseurl:            #"/Lagrange"
url:                #"https://lenpaul.github.io"
github:
  url:               "https://lenpaul.github.io/Lagrange"
author:
  name:              "John Mecham"
  email:             "jon.mecham@gmail.com"
  twitter:           # "paululele"
  instagram:         # "paululele"
  github:            "TheWiseLion"
  facebook:          # "Le.Paul.94"
  linkedin:          "thewiselion"
navigation:
- title: About
  url: /about
- title: Writing
  url: /writing
- title: Contact
  url: /contact

paginate:            5
disqus:              "bunchesofhunches.disqus.com"

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]
