# Site Settings
title:               Bunches Of Hunches
tagline:             
description:
baseurl:            #""
url:                #"https://thewiselion.github.io"
github:
  url:               #"https://thewiselion.github.io"
author:
  name:              "John Mecham"
  email:             "jon.mecham@gmail.com"
  twitter:           # "paululele"
  instagram:         # "paululele"
  github:            "TheWiseLion"
  facebook:          # "Le.Paul.94"
  linkedin:          "thewiselion"
navigation:
- title: About
  url: /about
- title: Writing
  url: /writing
- title: Contact
  url: /contact

paginate:            5
disqus:              "bunchesofhunches"

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]
